### PR TITLE
`FraxTest` Coverage

### PR DESCRIPTION
**Pull request by 0xJayPi**
### Description
Update functions coverage of `FraxTest` to reach 100%

### Changes
- Modified `TestSlotDump.sol`

### Related Issue
Related to https://github.com/FraxFinance/frax-standard-solidity/issues/18

### New coverage

| File                                              | % Lines         | % Statements    | % Branches    | % Funcs         |
|---------------------------------------------------|-----------------|-----------------|---------------|-----------------|
| src/FraxTest.sol                                  | 96.15% (25/26)  | 97.30% (36/37)  | 0.00% (0/1)   | 100.00% (7/7)   |

### CODE REVIEW

**Comment by 0xJayPi** [comment]
@pegahcarter pls review

**Review by pegahcarter — CHANGES_REQUESTED** [review]
Almost good to merge, just need to remove the `package-lock.json` from the PR.

**Comment by 0xJayPi** [comment]
I missed that one. Corrected now.

**Comment by pegahcarter** [comment]
@0xJayPi nice work :+1:

**Pull request merged**
